### ISSUE TITLE
value undefined when refresh prop is used

### ISSUE THREAD

**Issue by frontendphil** [signavio/kraken#259]
**Describe the bug**
We're running into an issue when we use the `refresh` property. Before the request is done the `pending` prop is already set to `false` even though no new `value` has been computed. This breaks the application and forces us to do more checks than actually necessary.

**Comment by frontendphil** [comment]
👍 from myself... Damn!

**Comment by SilentGert** [comment]
That's a really nasty one. Just ran into it as well. In my case the problem occurred when the `refresh` property changed for the first time. It looks like the actual action to fetch the data wasn't dispatched, yet, but the `value` was already reset to `undefined`. Therefore, `fulfilled` was `true` and `pending` `false`...
